---
title: "scRNA_Mouse_Spleen"
output: html_document
date: "2023-08-25"
---

```{r}
indir = "./GSE155006"
samples_dir = list.files(path = indir, full.names = T)
```

```{r}
select = samples_dir[grep("Spleen",samples_dir,ignore.case = T)]
```

```{r,message=FALSE}
library(Seurat)
library(tidyverse)
library(Matrix)
```

```{r}
#Load Seurat Objects and merge
#QC can be done in specific subset
n = length(select)
samples = character(length = n)
objs = list(n)
ctr = 1
for (i in select){
  sample_name = last(unlist(strsplit(i,split = "/")))
  obj_name = paste0(sample_name,"_object")
  objs[[ctr]] = assign(obj_name, CreateSeuratObject(counts = Read10X(i),min.cells = 5, min.features = 300))
  samples[ctr] = sample_name
  ctr = ctr + 1
}

```


```{r}
#Typically we expect 2 conditions
#orig.ident needs to be added afterwards because of duplication in cell name
whole = merge(eval(as.symbol(paste0(samples[1],"_object"))),y=eval(as.symbol(paste0(samples[2],"_object"))),add.cell.ids = samples,project = "Spleen")
```

```{r}
#An alternative way is to use a list to concatenate the objects
#If splicing of list is needed, we can do 
#whole = merge(objs[[1]],y=objs[[2]],orig.ident = samples,add.cell.ids = samples,project = "Spleen")
```

```{r}
rm(objs)
rm(Spleen_Aged_object)
rm(Spleen_Young_object)
gc()
```

```{r}
mito.genes <- c(grep("^MT-|^mt-", rownames(x = whole), value = T))
percent.mito <- Matrix::colSums(x = GetAssayData(object = whole, slot = 'counts')[mito.genes, ]) / Matrix::colSums(x = GetAssayData(object = whole, slot = 'counts'))
whole[['percent.mito']] <- percent.mito
```

```{r}
#If we want to add orig.ident manually and the group names have different lengths (meaning that we cannot use substring()), we can use range() and grep() as an alternative way.
aged_range = range(grep("Aged",rownames(whole@meta.data)))
young_range = range(grep("Young",rownames(whole@meta.data)))
whole@meta.data$orig.ident[aged_range[1]:aged_range[2]] = "Aged"
whole@meta.data$orig.ident[young_range[1]:young_range[2]] = "Young"
```

```{r}
ggplot(whole@meta.data)+
  geom_histogram(aes(x=percent.mito,y = after_stat(width*density*100)),bins = 100)+
  facet_wrap(vars(orig.ident),ncol=1)+
  geom_vline(xintercept = 0.05,col="red") +
  ylab("proportion")+
  xlab("percentage of mitochondrial RNA")
```

```{r}
ggplot(whole@meta.data, aes(x = log2(nFeature_RNA))) +
  geom_histogram(bins = 100, aes(y = stat(width*density*100))) +
  theme_classic() +
  facet_wrap(~orig.ident, ncol = 1) +
  geom_vline(xintercept = 8.5) + 
  geom_vline(xintercept = 10.5) + 
  ggtitle("nGene") +
  ylab("")
```

```{r}
whole$nFeature_RNA_log2 = log2(whole$nFeature_RNA)
cells.before <- length(colnames(x = whole))
print(cells.before)
whole <- subset(x = whole, subset = percent.mito < 0.05 & nFeature_RNA_log2 > 8.5)
cells.after <- length(colnames(x = whole))
print(cells.after)
```


```{r}
#Temporarily don't use SCTransform
#whole <- SCTransform(whole, vars.to.regress = c("nCount_RNA","percent.mito"), verbose = FALSE)
```

```{r}
whole <- NormalizeData(object = whole, normalization.method = "LogNormalize", scale.factor = 10000)
whole <- FindVariableFeatures(object = whole, selection.method = 'mean.var.plot', mean.cutoff = c(0.0125, 3), dispersion.cutoff = c(0.5, Inf))
whole@assays$RNA@var.features <-  whole@assays$RNA@var.features[!grepl("^TRA|^TRB|^IGH|^IGK|MAMU-A", whole@assays$RNA@var.features)]
whole <- ScaleData(object = whole, features = VariableFeatures(object = whole), vars.to.regress = c("nCount_RNA", "percent.mito"))
gc()
whole <- RunPCA(object = whole, verbose=FALSE)
```

```{r}
library(harmony)
```

```{r}
whole@meta.data$Subject <- gsub("_.*", "", whole@meta.data$orig.ident)
whole <- RunHarmony(whole, "Subject")
```
```{r}
DimPlot(whole,group.by = 'orig.ident',reduction = "pca")
```

```{r}
res.fld = "./"
whole <- whole %>% 
    RunUMAP(reduction = "harmony", dims = 1:20) %>% 
    FindNeighbors(reduction = "harmony", dims = 1:20) %>% 
    FindClusters(resolution = 0.5) %>% 
    identity()
save(whole, file = paste(res.fld, "whole_object.Robj", sep = ""))

## identify markers
whole.markers <- FindAllMarkers(object = whole,
                                only.pos = TRUE,
                                min.pct = 0.15,
                                thresh.use = 0.15)
write.table(whole.markers, paste(res.fld, "markers.tsv", sep = ""), sep="\t", quote=F, row.names=F)
```


```{r}
ElbowPlot(whole,ndims = 30)
```

```{r}
DimPlot(whole,reduction = "umap",group.by = "orig.ident")
```

```{r}
FeaturePlot(whole,features=c("Gzmk","Foxp3","Cd8a"),reduction = "umap",split.by = "orig.ident")
```

```{r}
RidgePlot(whole, features = c("Gzmk","Foxp3","Cd8a"), ncol = 3)
```

```{r}
identity = character(length(unique(whole.markers$cluster)))
identity[1] = "B Cell"
identity[2] = "B Cell"
identity[3] = "Th"
identity[4] = "Treg"
identity[5] = "Tcytotoxic"
identity[6] = "Tcytotoxic"
identity[7] = "Tcytotoxic"
identity[8] = "Unsure"
identity[8] = "Unsure"
identity[9] = "Unsure"
identity[10] = "Unsure"
#cluster 14 does not make sense since no marker satisfies the cutoff
#Clustering is not ideal
```

```{r}
#Try t-sne
whole = RunTSNE(whole,dims = 1:20)
```

```{r}
whole = FindClusters(whole, resolution = 0.1)
DimPlot(whole, reduction = "tsne")
```
```{r}
FeaturePlot(whole,c("Cd3d","Gzmk"),split.by = "orig.ident",reduction = "tsne")
```

```{r}
#may need to remove doublet
#check CD3 and CD19
FeaturePlot(whole,c("Cd3d","Cd19"),reduction = "tsne")
```

```{r}
head(whole@assays[["RNA"]]@scale.data[1:20,1:6])
```

```{r}
head(whole@assays[["RNA"]]@counts[1:20,1:6])
```

```{r}
#doublet removal code
Cd19_list = (whole@assays[["RNA"]]@counts[grep("Cd19",rownames(whole@assays[["RNA"]]@counts)),] > 0)
Cd3d_list = (whole@assays[["RNA"]]@counts[grep("Cd3d",rownames(whole@assays[["RNA"]]@counts)),] > 0)
doub1 = colnames(whole)[Cd19_list & Cd3d_list]


```

```{r}
whole@assays[["RNA"]]@counts = whole@assays[["RNA"]]@counts[,!colnames(whole@assays[["RNA"]]@counts)%in% doub1]
```

```{r}
cells.after <- length(colnames(x = whole))
print(cells.after)
```

```{r}
whole <- whole %>% 
    RunUMAP(reduction = "harmony", dims = 1:20) %>% 
    FindNeighbors(reduction = "harmony", dims = 1:20) %>% 
    FindClusters(resolution = 0.5) %>% 
    identity()
```

```{r}
FeaturePlot(whole, features = c("Gzmk","Cd19","Cd3d"), reduction = "umap",split.by = "orig.ident")
```

```{r}
ggplot(whole@meta.data)+
  geom_histogram(aes(x = nFeature_RNA_log2,fill = orig.ident),bins = 50)
```

