---
title: "QC_preprocesing_Single"
output: html_document
date: "2023-08-28"
---

```{r}
#All package load here
library(SoupX)#Soup removal
library(DoubletFinder)#Doublet removal
library(miQC)#mito percentage filtering
library(data.table)
library(SeuratWrappers)
```

```{r}
#Load data; provide single sample name for indir
indir = "./outs" #Can be made into a command-line input
outdir = "."
sample = "ALAW_3" #command-line input
#samples_dir = list.files(path = indir, full.names = T)#list directories for SoupX
toc <- Seurat::Read10X(paste(indir,"/", sample, "/filtered_feature_bc_matrix", sep = ""))
tod <- Seurat::Read10X(paste(indir,"/", sample, "/raw_feature_bc_matrix", sep = ""))
meta <- fread(paste(indir, "/",sample, "/analysis/clustering/graphclust/clusters.csv", sep = ""))

```

```{r}
#prep clusterinfo
clusters <- meta$Cluster
names(clusters) <- meta$Barcode
```

```{r}
## run soupx
sc <- SoupChannel(tod, toc, calcSoupProfile = FALSE)
sc <- setClusters(sc, clusters)
sc <- estimateSoup(sc)
sc <- autoEstCont(sc)
out <- adjustCounts(sc)
```

```{r}
#mitochondrial removal 
#create object
obj = CreateSeuratObject(out) #it is possible to assign names based on sample name with some downstream technical challenges
#output of eval is possibly non-writable
```

```{r}
obj[["percent.mt"]] = PercentageFeatureSet(object = obj, pattern = "^MT-|^mt-")
jpeg("percent_mt-nFeature_RNA")
FeatureScatter(obj, feature1 = "nFeature_RNA", feature2 = "percent.mt")
dev.off()
```
```{r}
obj <- RunMiQC(obj, percent.mt = "percent.mt", nFeature_RNA = "nFeature_RNA", posterior.cutoff = 0.75,
    model.slot = "flexmix_model")
```

```{r}
jpeg("MiQCplot.jpeg")
PlotMiQC(obj, color.by = "miQC.probability") + ggplot2::scale_color_gradient(low = "grey", high = "purple")
dev.off()
```

```{r}
jpeg("miQC_keep.jpeg")
PlotMiQC(obj, color.by = "miQC.keep")
dev.off()
```


```{r}
obj_filtered <- subset(obj, miQC.keep == "keep")
obj_filtered
```

```{r}
#Visualizing and checking: non-filtered
obj <- NormalizeData(obj)
obj <- FindVariableFeatures(obj, selection.method = "vst", nfeatures = 2000)
obj <- ScaleData(obj)
obj <- RunPCA(obj)
obj <- RunUMAP(obj, dims = 1:10)
```


```{r}
#Visualizing and checking: filtered
obj_filtered <- NormalizeData(obj_filtered)
obj_filtered <- FindVariableFeatures(obj_filtered, selection.method = "vst", nfeatures = 2000)
obj_filtered <- ScaleData(obj_filtered)
obj_filtered <- RunPCA(obj_filtered)
obj_filtered <- RunUMAP(obj_filtered, dims = 1:10)
```

```{r}
jpeg("filtering comparison.jpeg")
plt1 <- FeaturePlot(obj,features = "percent.mt",reduction = "umap") + ggtitle("percent.mt unfiltered")
plt2 <- FeaturePlot(obj_filtered,features = "percent.mt",reduction = "umap") + ggtitle("percent.mt filtered")
plt3 <- FeaturePlot(obj,features = "nFeature_RNA",reduction = "umap") + ggtitle("nGenes unfiltered")
plt4 <- FeaturePlot(obj_filtered,features =  "nFeature_RNA",reduction = "umap") + ggtitle("nGenes filtered")
plot_grid(plt1,plt2,plt3,plt4,labels = "AUTO",nrow = 2)#need "cowplot"
dev.off()
```


```{r}
#perparing for DoubleFinder
# Find significant PCs
stdv <- obj_filtered[["pca"]]@stdev
sum.stdv <- sum(obj_filtered[["pca"]]@stdev)
percent.stdv <- (stdv / sum.stdv) * 100
cumulative <- cumsum(percent.stdv)
co1 <- which(cumulative > 90 & percent.stdv < 5)[1]
co2 <- sort(which((percent.stdv[1:length(percent.stdv) - 1] - 
                   percent.stdv[2:length(percent.stdv)]) > 0.1), 
                   decreasing = T)[1] + 1
min.pc <- min(co1, co2)
```

```{r}
obj_filtered <- RunUMAP(obj_filtered, dims = 1:min.pc)
obj_filtered <- FindNeighbors(object = obj_filtered, dims = 1:min.pc)              
obj_filtered <- FindClusters(object = obj_filtered, resolution = 0.1)
```


```{r}
sweep.res.list <- paramSweep_v3(obj_filtered, PCs = 1:min.pc, sct = FALSE,num.cores = detectCores() - 1)
sweep.stats <- summarizeSweep(sweep.res.list, GT = FALSE)
bcmvn <- find.pK(sweep.stats)
```

```{r}
optimal.pk = as.numeric(levels(bcmvn$pK)[which.max(bcmvn$BCmetric)])
```

```{r}
annotations <- obj_filtered@meta.data$seurat_clusters
homotypic.prop <- modelHomotypic(annotations) 
nExp.poi <- round(optimal.pk * nrow(obj_filtered@meta.data)) ## Assuming 7.5% doublet formation rate - tailor for your dataset
nExp.poi.adj <- round(nExp.poi * (1 - homotypic.prop))
  
```


```{r}
obj_filtered <- doubletFinder_v3(seu = obj_filtered, 
                                   PCs = 1:min.pc, 
                                   pK = optimal.pk,
                                   nExp = nExp.poi.adj)
metadata <- obj_filtered@meta.data
```

```{r}
colnames(metadata)[(length(colnames(metadata)))] <- "doublet_finder"
obj_filtered@meta.data <- metadata
obj_filtered <- subset(obj_filtered, doublet_finder == "Singlet")
obj_filtered
save(obj_filtered, file = paste(outdir, "filtered_object.Robj", sep = "/"))
```


